export const data = [
	{
		id: 1,
		url: 'img/products/1.png',
		title: "ELLERY X M'O CAPSULE",
		text: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
		price: '52.00',
		color: 'red',
		size: 'xl',
	},
	{
		id: 2,
		url: 'img/products/2.png',
		title: "ELLERY X M'O CAPSULE",
		text: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
		price: '59.25',
		color: 'blue',
		size: 'xs',
	},
	{
		id: 3,
		url: 'img/products/3.png',
		title: "ELLERY X M'O CAPSULE",
		text: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
		price: '102.04',
		color: 'green',
		size: 'l',
	},
	{
		id: 4,
		url: 'img/products/4.png',
		title: "ELLERY X M'O CAPSULE",
		text: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
		price: '13.50',
		color: 'black',
		size: 'xxl',
	},
	{
		id: 5,
		url: 'img/products/5.png',
		title: "ELLERY X M'O CAPSULE",
		text: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
		price: '72.34',
		color: 'cian',
		size: 'xs',
	},
	{
		id: 6,
		url: 'img/products/6.png',
		title: "ELLERY X M'O CAPSULE",
		text: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
		price: '29.10',
		color: 'tomato',
		size: 'm',
	},
];
